### ISSUE TITLE
Статья на хабре

### ISSUE THREAD

**Issue by revolexGeek** [sudovag3/foundry-middle-part1#1]
Со статьей на хабре что-то не так :(
![habr is dead](https://github.com/sudovag3/foundry-course/assets/86723750/3c796664-1f35-4656-bf04-5dc01c5a3ba7)

**Comment by sudovag3** [comment]
Статьи выкладываются по расписанию, а репозиторий обновляется заранее. В данный момент 3-я часть уже доступна, сейчас не доступна только 4 часть, она выйдет завтра в 17:00. Приятного чтения!
